In [1]:
import pandas as pd
import numpy as np

In [12]:
zet = pd.read_csv('Lobel ZET CSV.csv')

In [13]:
zet.head()

,DATUM,SMJER,START,STOP,ZET LINIJA,TRAJANJE,OPASKA,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,6.2.2024,Šva-Trg,8:48,9:27,146 + 6,0:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7.2.2024,Šva-Trg,8:31,9:10,146 + 6,0:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8.2.2024,Šva-Trg,9:18,9:59,136 + 6,0:41,kontrola u 6,NaN,NaN,NaN,NaN,NaN,NaN
3,9.2.2024,Šva-Trg,9:20,10:06,136 + 6,0:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12.2.2024.,Šva-Trg,8:40,9:13,136 + 6,0:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
zet = zet.drop('Unnamed: 7', axis=1)
zet = zet.drop('Unnamed: 8', axis=1)
zet = zet.drop('Unnamed: 9', axis=1)
zet = zet.drop('Unnamed: 10', axis=1)
zet = zet.drop('Unnamed: 11', axis=1)
zet = zet.drop('Unnamed: 12', axis=1)

In [31]:
zet.head(20)

         DATUM    SMJER  START   STOP ZET LINIJA TRAJANJE          OPASKA
0     6.2.2024  Šva-Trg   8:48   9:27    146 + 6     0:39             NaN
1     7.2.2024  Šva-Trg   8:31   9:10    146 + 6     0:39             NaN
2     8.2.2024  Šva-Trg   9:18   9:59    136 + 6     0:41    kontrola u 6
3     9.2.2024  Šva-Trg   9:20  10:06    136 + 6     0:46             NaN
4   12.2.2024.  Šva-Trg   8:40   9:13    136 + 6     0:33             NaN
5   13.2.2024.  Šva-Trg   9:26  10:05    136 + 6     0:39  kontrola u 136
6   14.2.2024.  Šva-Trg   8:41   9:23   146 + 11     0:42             NaN
7   15.2.2024.  Šva-Trg   8:15   9:01    136 + 6     0:46             NaN
8    16.2.2024  Šva-Trg   8:27   9:08    136 + 6     0:41             NaN
9    19.2.2024  Šva-Trg   8:03   8:39   136 + 11     0:36             NaN
10   20.2.2024  Šva-Trg   8:55   9:30    136 + 6     0:35  kontrola u 136
11   21.2.2024  Šva-Trg   9:17   9:55    136 + 6     0:38    kontrola u 6
12   22.2.2024  Šva-Trg   8:03   8:32   136 + 11     0:29             NaN
13   23.2.2024  Šva-Trg   9:02   9:33   146 + 11     0:31             NaN
14   24.2.2024  Šva-Trg  11:52  12:45   136 + 11     0:53             NaN
15   25.2.2024  Šva-Trg  10:02  10:45    136 + 6     0:43             NaN
16   26.2.2024  Šva-Trg   7:13   7:50    136 + 6     0:37             NaN
17   27.2.2024  Šva-Trg   8:54   9:33    136 + 6     0:39             NaN
18   28.2.2024  Šva-Trg   8:57   9:40    136 + 6     0:43             NaN
19   29.2.2024  Šva-Trg   9:50  10:29   146 + 11     0:39             NaN

In [37]:
102%100

2

In [46]:
vremena = zet['TRAJANJE'].to_list()
vremena_min = [float(x.replace(':','.'))*100 for x in vremena]
vremena_min

[39.0,
 39.0,
 41.0,
 46.0,
 33.0,
 39.0,
 42.0,
 46.0,
 41.0,
 36.0,
 35.0,
 38.0,
 28.999999999999996,
 31.0,
 53.0,
 43.0,
 37.0,
 39.0,
 43.0,
 39.0,
 32.0,
 38.0,
 36.0,
 33.0,
 44.0,
 33.0,
 34.0,
 41.0,
 34.0,
 39.0,
 33.0,
 44.0,
 43.0,
 49.0,
 43.0,
 34.0,
 42.0,
 28.000000000000004,
 33.0,
 31.0,
 34.0,
 38.0,
 31.0,
 33.0,
 40.0,
 28.000000000000004,
 33.0,
 41.0,
 56.99999999999999,
 24.0,
 41.0,
 28.999999999999996,
 41.0,
 39.0,
 48.0,
 38.0,
 37.0,
 33.0,
 43.0,
 46.0,
 43.0,
 32.0,
 25.0,
 24.0,
 40.0,
 104.0,
 39.0,
 32.0,
 32.0,
 38.0,
 35.0,
 28.000000000000004,
 22.0,
 33.0,
 25.0,
 31.0,
 26.0,
 28.999999999999996,
 34.0,
 56.99999999999999,
 32.0,
 28.000000000000004,
 33.0,
 121.0,
 28.000000000000004,
 30.0,
 43.0,
 27.0,
 39.0,
 34.0,
 35.0,
 41.0,
 32.0,
 31.0,
 28.999999999999996,
 36.0,
 26.0,
 32.0,
 35.0,
 46.0,
 57.99999999999999,
 37.0,
 36.0,
 39.0,
 38.0,
 35.0,
 34.0,
 54.0,
 35.0,
 39.0,
 35.0,
 31.0,
 100.0,
 57.99999999999999,
 53.0,
 46.0,
 47.0,
 51.0]

In [44]:
vremena_min = [39.0,39.0,41.0,46.0,33.0,39.0,42.0,46.0,41.0,36.0,35.0,38.0,29,
 31.0,53.0,43.0,37.0,39.0,43.0,39.0,32.0,38.0,36.0,33.0,44.0,33.0,34.0,41.0,
 34.0,39.0,33.0,44.0,43.0,49.0,43.0,34.0,42.0,2933.0,31.0,34.0,38.0,31.0,33.0,40.0,
 29,33.0,41.0,57.0,24.0,41.0,29.0,41.0,39.0,48.0,38.0,37.0,33.0,43.0,46.0,43.0,32.0,
 25.0,24.0,40.0,64.0,39.0,32.0,32.0,38.0,35.0,28.0,22.0,33.0,25.0,31.0,26.0,29.0,34.0,57.0,
 32.0,28.0,33.0,81.0,29.0,30.0,43.0,27.0,39.0,34.0,35.0,41.0,32.0,31.0,29.0,36.0,26.0,32.0,35.0,
 46.0,58.0,37.0,36.0,39.0,38.0,35.0,34.0,54.0,35.0,39.0,35.0,31.0,60.0,58.0,53.0,46.0,47.0,51.0]

In [45]:
zet['trajanje min'] = vremena_min
zet.head()

ValueError: Length of values (117) does not match length of index (118)

- scatterplot: x os - sati u danu, y-osi - vrijeme potrebno
- razlicite boje oznacuju smjer kretanja

- sve gdje je s trga na svarcansku treba jos 2 minute
-